In [1]:
import numpy as np

In [2]:
  #basic addition

In [4]:
n1=np.array([10,20,30])
n1=n1+5
n1

array([15, 25, 35])

In [6]:
n1=n1-5
n1

array([ 5, 15, 25])

In [7]:
n1=n1*10
n1

array([ 50, 150, 250])

In [9]:
n2=n1*2
n2

array([100, 300, 500])

In [10]:
n2=n2/100

In [11]:
n2


array([1., 3., 5.])