In [3]:
import numpy as np

In [ ]:
#cheacking shape of array

In [4]:
n=np.array([[12,22,33],[22,44,66]])


In [5]:
n


array([[12, 22, 33],
       [22, 44, 66]])

In [6]:
n.shape

(2, 3)

In [7]:
n.shape=(3,2)

In [8]:
print(n)

[[12 22]
 [33 22]
 [44 66]]


In [10]:
n.shape=(6,1)

In [11]:
print(n)

[[12]
 [22]
 [33]
 [22]
 [44]
 [66]]


In [ ]:
           #2 array ko stack ya jodne ke liye

In [14]:

n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [15]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [16]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])